# Generated by Django 4.1.4 on 2022-12-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Upi_id', models.CharField(max_length=50)),
                ('payment_Img', models.ImageField(upload_to='images/')),
                ('Otp', models.CharField(max_length=50)),
            ],
        ),
    ]
